export const columnsByMission = {
  TESS: [
    { value: 'tid', label: 'TESS Input Catalog ID' },
    { value: 'toi', label: 'TESS Object of Interest' },
    { value: 'toipfx', label: 'TESS Object of Interest Prefix' },
    { value: 'ctoi_alias', label: 'Community TESS Object of Interest Alias' },
    { value: 'pl_pnum', label: 'Number of Planet Candidates' },
    { value: 'tfopwg_disp', label: 'TFOPWG Disposition' },
    { value: 'rastr', label: 'RA [sexagesimal]' },
    { value: 'ra', label: 'RA [deg]' },
    { value: 'decstr', label: 'Dec [sexagesimal]' },
    { value: 'dec', label: 'Dec [deg]' },
    { value: 'st_pmra', label: 'PMRA [mas/yr]' },
    { value: 'st_pmdec', label: 'PMDec [mas/yr]' },
    { value: 'pl_tranmid', label: 'Planet Transit Midpoint [BJD]' },
    { value: 'pl_orbper', label: 'Planet Orbital Period [days]' },
    { value: 'pl_trandurh', label: 'Planet Transit Duration [hours]' },
    { value: 'pl_trandep', label: 'Planet Transit Depth [ppm]' },
    { value: 'pl_rade', label: 'Planet Radius [R_Earth]' },
    { value: 'pl_insol', label: 'Planet Insolation [Earth flux]' },
    { value: 'pl_eqt', label: 'Planet Equilibrium Temperature [K]' },
    { value: 'st_tmag', label: 'TESS Magnitude' },
    { value: 'st_dist', label: 'Stellar Distance [pc]' },
    { value: 'st_teff', label: 'Stellar Effective Temperature [K]' },
    { value: 'st_logg', label: 'Stellar log(g) [cm/s**2]' },
    { value: 'st_rad', label: 'Stellar Radius [R_Sun]' },
    { value: 'toi_created', label: 'TOI Creation Date' },
    { value: 'rowupdate', label: 'Date of Last Update' },
  ],
  PS: [
    { value: 'pl_name', label: 'Planet Name' },
    { value: 'hostname', label: 'Host Name' },
    { value: 'pl_letter', label: 'Planet Letter' },
    { value: 'hd_name', label: 'HD ID' },
    { value: 'hip_name', label: 'HIP ID' },
    { value: 'tic_id', label: 'TIC ID' },
    { value: 'gaia_id', label: 'GAIA ID' },
    { value: 'default_flag', label: 'Default Parameter Set' },
    { value: 'sy_snum', label: 'Number of Stars' },
    { value: 'sy_pnum', label: 'Number of Planets' },
    { value: 'sy_mnum', label: 'Number of Moons' },
    { value: 'cb_flag', label: 'Circumbinary Flag' },
    { value: 'discoverymethod', label: 'Discovery Method' },
    { value: 'disc_year', label: 'Discovery Year' },
    { value: 'disc_refname', label: 'Discovery Reference' },
    { value: 'disc_pubdate', label: 'Discovery Publication Date' },
    { value: 'disc_locale', label: 'Discovery Locale' },
    { value: 'disc_facility', label: 'Discovery Facility' },
    { value: 'disc_telescope', label: 'Discovery Telescope' },
    { value: 'disc_instrument', label: 'Discovery Instrument' },
    { value: 'rv_flag', label: 'Detected by Radial Velocity Variations' },
    { value: 'pul_flag', label: 'Detected by Pulsar Timing Variations' },
    { value: 'ptv_flag', label: 'Detected by Pulsation Timing Variations' },
    { value: 'tran_flag', label: 'Detected by Transits' },
    { value: 'ast_flag', label: 'Detected by Astrometric Variations' },
    { value: 'obm_flag', label: 'Detected by Orbital Brightness Modulations' },
    { value: 'micro_flag', label: 'Detected by Microlensing' },
    { value: 'etv_flag', label: 'Detected by Eclipse Timing Variations' },
    { value: 'ima_flag', label: 'Detected by Imaging' },
    { value: 'dkin_flag', label: 'Detected by Disk Kinematics' },
    { value: 'soltype', label: 'Solution Type' },
    { value: 'pl_controv_flag', label: 'Controversial Flag' },
    { value: 'pl_refname', label: 'Planetary Parameter Reference' },
    { value: 'pl_orbper', label: 'Orbital Period [days]' },
    { value: 'pl_orbpererr1', label: 'Orbital Period Upper Unc. [days]' },
    { value: 'pl_orbpererr2', label: 'Orbital Period Lower Unc. [days]' },
    { value: 'pl_orbperlim', label: 'Orbital Period Limit Flag' },
    { value: 'pl_orbsmax', label: 'Orbit Semi-Major Axis [au])' },
    { value: 'pl_orbsmaxerr1', label: 'Orbit Semi-Major Axis Upper Unc. [au]' },
    { value: 'pl_orbsmaxerr2', label: 'Orbit Semi-Major Axis Lower Unc. [au]' },
    { value: 'pl_orbsmaxlim', label: 'Orbit Semi-Major Axis Limit Flag' },
    { value: 'pl_rade', label: 'Planet Radius [Earth Radius]' },
    { value: 'pl_radeerr1', label: 'Planet Radius Upper Unc. [Earth Radius]' },
    { value: 'pl_radeerr2', label: 'Planet Radius Lower Unc. [Earth Radius]' },
    { value: 'pl_radelim', label: 'Planet Radius Limit Flag' },
    { value: 'pl_radj', label: 'Planet Radius [Jupiter Radius]' },
    { value: 'pl_radjerr1', label: 'Planet Radius Upper Unc. [Jupiter Radius]' },
    { value: 'pl_radjerr2', label: 'Planet Radius Lower Unc. [Jupiter Radius]' },
    { value: 'pl_radjlim', label: 'Planet Radius Limit Flag' },
    { value: 'pl_masse', label: 'Planet Mass [Earth Mass]' },
    { value: 'pl_masseerr1', label: 'Planet Mass [Earth Mass] Upper Unc.' },
    { value: 'pl_masseerr2', label: 'Planet Mass [Earth Mass] Lower Unc.' },
    { value: 'pl_masselim', label: 'Planet Mass [Earth Mass] Limit Flag' },
    { value: 'pl_massj', label: 'Planet Mass [Jupiter Mass]' },
    { value: 'pl_massjerr1', label: 'Planet Mass [Jupiter Mass] Upper Unc.' },
    { value: 'pl_massjerr2', label: 'Planet Mass [Jupiter Mass] Lower Unc.' },
    { value: 'pl_massjlim', label: 'Planet Mass [Jupiter Mass] Limit Flag' },
    { value: 'pl_msinie', label: 'Planet Mass*sin(i) [Earth Mass]' },
    { value: 'pl_msinieerr1', label: 'Planet Mass*sin(i) [Earth Mass] Upper Unc.' },
    { value: 'pl_msinieerr2', label: 'Planet Mass*sin(i) [Earth Mass] Lower Unc.' },
    { value: 'pl_msinielim', label: 'Planet Mass*sin(i) [Earth Mass] Limit Flag' },
    { value: 'pl_msinij', label: 'Planet Mass*sin(i) [Jupiter Mass]' },
    { value: 'pl_msinijerr1', label: 'Planet Mass*sin(i) [Jupiter Mass] Upper Unc.' },
    { value: 'pl_msinijerr2', label: 'Planet Mass*sin(i) [Jupiter Mass] Lower Unc.' },
    { value: 'pl_msinijlim', label: 'Planet Mass*sin(i) [Jupiter Mass] Limit Flag' },
    { value: 'pl_cmasse', label: 'Planet Mass*sin(i)/sin(i) [Earth Mass]' },
    { value: 'pl_cmasseerr1', label: 'Planet Mass*sin(i)/sin(i) [Earth Mass] Upper Unc.' },
    { value: 'pl_cmasseerr2', label: 'Planet Mass*sin(i)/sin(i) [Earth Mass] Lower Unc.' },
    { value: 'pl_cmasselim', label: 'Planet Mass*sin(i)/sin(i) [Earth Mass] Limit Flag' },
    { value: 'pl_cmassj', label: 'Planet Mass*sin(i)/sin(i) [Jupiter Mass]' },
    { value: 'pl_cmassjerr1', label: 'Planet Mass*sin(i)/sin(i) [Jupiter Mass] Upper Unc.' },
    { value: 'pl_cmassjerr2', label: 'Planet Mass*sin(i)/sin(i) [Jupiter Mass] Lower Unc.' },
    { value: 'pl_cmassjlim', label: 'Planet Mass*sin(i)/sin(i) [Jupiter Mass] Limit Flag' },
    { value: 'pl_bmasse', label: 'Planet Mass or Mass*sin(i) [Earth Mass]' },
    { value: 'pl_bmasseerr1', label: 'Planet Mass or Mass*sin(i) [Earth Mass] Upper Unc.' },
    { value: 'pl_bmasseerr2', label: 'Planet Mass or Mass*sin(i) [Earth Mass] Lower Unc.' },
    { value: 'pl_bmasselim', label: 'Planet Mass or Mass*sin(i) [Earth Mass] Limit Flag' },
    { value: 'pl_bmassj', label: 'Planet Mass or Mass*sin(i) [Jupiter Mass]' },
    { value: 'pl_bmassjerr1', label: 'Planet Mass or Mass*sin(i) [Jupiter Mass] Upper Unc.' },
    { value: 'pl_bmassjerr2', label: 'Planet Mass or Mass*sin(i) [Jupiter Mass] Lower Unc.' },
    { value: 'pl_bmassjlim', label: 'Planet Mass or Mass*sin(i) [Jupiter Mass] Limit Flag' },
    { value: 'pl_bmassprov', label: 'Planet Mass or Mass*sin(i) Provenance' },
    { value: 'pl_dens', label: 'Planet Density [g/cm**3]' },
    { value: 'pl_denserr1', label: 'Planet Density Upper Unc. [g/cm**3]' },
    { value: 'pl_denserr2', label: 'Planet Density Lower Unc. [g/cm**3]' },
    { value: 'pl_denslim', label: 'Planet Density Limit Flag' },
    { value: 'pl_orbeccen', label: 'Eccentricity' },
    { value: 'pl_orbeccenerr1', label: 'Eccentricity Upper Unc.' },
    { value: 'pl_orbeccenerr2', label: 'Eccentricity Lower Unc.' },
    { value: 'pl_orbeccenlim', label: 'Eccentricity Limit Flag' },
    { value: 'pl_insol', label: 'Insolation Flux [Earth Flux]' },
    { value: 'pl_insolerr1', label: 'Insolation Flux Upper Unc. [Earth Flux]' },
    { value: 'pl_insolerr2', label: 'Insolation Flux Lower Unc. [Earth Flux]' },
    { value: 'pl_insollim', label: 'Insolation Flux Limit Flag' },
    { value: 'pl_eqt', label: 'Equilibrium Temperature [K]' },
    { value: 'pl_eqterr1', label: 'Equilibrium Temperature Upper Unc. [K]' },
    { value: 'pl_eqterr2', label: 'Equilibrium Temperature Lower Unc. [K]' },
    { value: 'pl_eqtlim', label: 'Equilibrium Temperature Limit Flag' },
    { value: 'pl_orbincl', label: 'Inclination [deg]' },
    { value: 'pl_orbinclerr1', label: 'Inclination Upper Unc. [deg]' },
    { value: 'pl_orbinclerr2', label: 'Inclination Lower Unc. [deg]' },
    { value: 'pl_orbincllim', label: 'Inclination Limit Flag' },
    { value: 'pl_tranmid', label: 'Transit Midpoint [days]' },
    { value: 'pl_tranmiderr1', label: 'Transit Midpoint Upper Unc. [days]' },
    { value: 'pl_tranmiderr2', label: 'Transit Midpoint Lower Unc. [days]' },
    { value: 'pl_tranmidlim', label: 'Transit Midpoint Limit Flag' },
    { value: 'pl_tsystemref', label: 'Time Reference Frame and Standard' },
    { value: 'ttv_flag', label: 'Data show Transit Timing Variations' },
    { value: 'pl_imppar', label: 'Impact Parameter' },
    { value: 'pl_impparerr1', label: 'Impact Parameter Upper Unc.' },
    { value: 'pl_impparerr2', label: 'Impact Parameter Lower Unc.' },
    { value: 'pl_impparlim', label: 'Impact Parameter Limit Flag' },
    { value: 'pl_trandep', label: 'Transit Depth [%]' },
    { value: 'pl_trandeperr1', label: 'Transit Depth Upper Unc. [%]' },
    { value: 'pl_trandeperr2', label: 'Transit Depth Lower Unc. [%]' },
    { value: 'pl_trandeplim', label: 'Transit Depth Limit Flag' },
    { value: 'pl_trandur', label: 'Transit Duration [hours]' },
    { value: 'pl_trandurerr1', label: 'Transit Duration Upper Unc. [hours]' },
    { value: 'pl_trandurerr2', label: 'Transit Duration Lower Unc. [hours]' },
    { value: 'pl_trandurlim', label: 'Transit Duration Limit Flag' },
    { value: 'pl_ratdor', label: 'Ratio of Semi-Major Axis to Stellar Radius' },
    { value: 'pl_ratdorerr1', label: 'Ratio of Semi-Major Axis to Stellar Radius Upper Unc.' },
    { value: 'pl_ratdorerr2', label: 'Ratio of Semi-Major Axis to Stellar Radius Lower Unc.' },
    { value: 'pl_ratdorlim', label: 'Ratio of Semi-Major Axis to Stellar Radius Limit Flag' },
    { value: 'pl_ratror', label: 'Ratio of Planet to Stellar Radius' },
    { value: 'pl_ratrorerr1', label: 'Ratio of Planet to Stellar Radius Upper Unc.' },
    { value: 'pl_ratrorerr2', label: 'Ratio of Planet to Stellar Radius Lower Unc.' },
    { value: 'pl_ratrorlim', label: 'Ratio of Planet to Stellar Radius Limit Flag' },
    { value: 'pl_occdep', label: 'Occultation Depth [%]' },
    { value: 'pl_occdeperr1', label: 'Occultation Depth Upper Unc. [%]' },
    { value: 'pl_occdeperr2', label: 'Occultation Depth Lower Unc. [%]' },
    { value: 'pl_occdeplim', label: 'Occultation Depth Limit Flag' },
    { value: 'pl_orbtper', label: 'Epoch of Periastron [days]' },
    { value: 'pl_orbtpererr1', label: 'Epoch of Periastron Upper Unc. [days]' },
    { value: 'pl_orbtpererr2', label: 'Epoch of Periastron Lower Unc. [days]' },
    { value: 'pl_orbtperlim', label: 'Epoch of Periastron Limit Flag' },
    { value: 'pl_orbtper_systemref', label: 'Epoch of Periastron Time System Frame and Standard' },
    { value: 'pl_orblper', label: 'Argument of Periastron [deg]' },
    { value: 'pl_orblpererr1', label: 'Argument of Periastron Upper Unc. [deg]' },
    { value: 'pl_orblpererr2', label: 'Argument of Periastron Lower Unc. [deg]' },
    { value: 'pl_orblperlim', label: 'Argument of Periastron Limit Flag' },
    { value: 'pl_rvamp', label: 'Radial Velocity Amplitude [m/s]' },
    { value: 'pl_rvamperr1', label: 'Radial Velocity Amplitude Upper Unc. [m/s]' },
    { value: 'pl_rvamperr2', label: 'Radial Velocity Amplitude Lower Unc. [m/s]' },
    { value: 'pl_rvamplim', label: 'Radial Velocity Amplitude Limit Flag' },
    { value: 'pl_projobliq', label: 'Projected Obliquity [deg]' },
    { value: 'pl_projobliqerr1', label: 'Projected Obliquity Upper Unc. [deg]' },
    { value: 'pl_projobliqerr2', label: 'Projected Obliquity Lower Unc. [deg]' },
    { value: 'pl_projobliqlim', label: 'Projected Obliquity Limit Flag' },
    { value: 'pl_trueobliq', label: 'True Obliquity [deg]' },
    { value: 'pl_trueobliqerr1', label: 'True Obliquity Upper Unc. [deg]' },
    { value: 'pl_trueobliqerr2', label: 'True Obliquity Lower Unc. [deg]' },
    { value: 'pl_trueobliqlim', label: 'True Obliquity Limit Flag' },
    { value: 'st_refname', label: 'Stellar Parameter Reference' },
    { value: 'st_spectype', label: 'Spectral Type' },
    { value: 'st_teff', label: 'Stellar Effective Temperature [K]' },
    { value: 'st_tefferr1', label: 'Stellar Effective Temperature Upper Unc. [K]' },
    { value: 'st_tefferr2', label: 'Stellar Effective Temperature Lower Unc. [K]' },
    { value: 'st_tefflim', label: 'Stellar Effective Temperature Limit Flag' },
    { value: 'st_rad', label: 'Stellar Radius [Solar Radius]' },
    { value: 'st_raderr1', label: 'Stellar Radius Upper Unc. [Solar Radius]' },
    { value: 'st_raderr2', label: 'Stellar Radius Lower Unc. [Solar Radius]' },
    { value: 'st_radlim', label: 'Stellar Radius Limit Flag' },
    { value: 'st_mass', label: 'Stellar Mass [Solar mass]' },
    { value: 'st_masserr1', label: 'Stellar Mass Upper Unc. [Solar mass]' },
    { value: 'st_masserr2', label: 'Stellar Mass Lower Unc. [Solar mass]' },
    { value: 'st_masslim', label: 'Stellar Mass Limit Flag' },
    { value: 'st_met', label: 'Stellar Metallicity [dex]' },
    { value: 'st_meterr1', label: 'Stellar Metallicity Upper Unc. [dex]' },
    { value: 'st_meterr2', label: 'Stellar Metallicity Lower Unc. [dex]' },
    { value: 'st_metlim', label: 'Stellar Metallicity Limit Flag' },
    { value: 'st_metratio', label: 'Stellar Metallicity Ratio' },
    { value: 'st_lum', label: 'Stellar Luminosity [log(Solar)]' },
    { value: 'st_lumerr1', label: 'Stellar Luminosity Upper Unc. [log(Solar)]' },
    { value: 'st_lumerr2', label: 'Stellar Luminosity Lower Unc. [log(Solar)]' },
    { value: 'st_lumlim', label: 'Stellar Luminosity Limit Flag' },
    { value: 'st_logg', label: 'Stellar Surface Gravity [log10(cm/s**2)]' },
    { value: 'st_loggerr1', label: 'Stellar Surface Gravity Upper Unc. [log10(cm/s**2)]' },
    { value: 'st_loggerr2', label: 'Stellar Surface Gravity Lower Unc. [log10(cm/s**2)]' },
    { value: 'st_logglim', label: 'Stellar Surface Gravity Limit Flag' },
    { value: 'st_age', label: 'Stellar Age [Gyr]' },
    { value: 'st_ageerr1', label: 'Stellar Age Upper Unc. [Gyr]' },
    { value: 'st_ageerr2', label: 'Stellar Age Lower Unc. [Gyr]' },
    { value: 'st_agelim', label: 'Stellar Age Limit Flag' },
    { value: 'st_dens', label: 'Stellar Density [g/cm**3]' },
    { value: 'st_denserr1', label: 'Stellar Density Upper Unc. [g/cm**3]' },
    { value: 'st_denserr2', label: 'Stellar Density Lower Unc. [g/cm**3]' },
    { value: 'st_denslim', label: 'Stellar Density Limit Flag' },
    { value: 'st_vsin', label: 'Stellar Rotational Velocity [km/s]' },
    { value: 'st_vsinerr1', label: 'Stellar Rotational Velocity [km/s] Upper Unc.' },
    { value: 'st_vsinerr2', label: 'Stellar Rotational Velocity [km/s] Lower Unc.' },
    { value: 'st_vsinlim', label: 'Stellar Rotational Velocity Limit Flag' },
    { value: 'st_rotp', label: 'Stellar Rotational Period [days]' },
    { value: 'st_rotperr1', label: 'Stellar Rotational Period [days] Upper Unc.' },
    { value: 'st_rotperr2', label: 'Stellar Rotational Period [days] Lower Unc.' },
    { value: 'st_rotplim', label: 'Stellar Rotational Period Limit Flag' },
    { value: 'st_radv', label: 'Stellar Radial Velocity [km/s]' },
    { value: 'st_radverr1', label: 'Stellar Radial Velocity Upper Unc. [km/s]' },
    { value: 'st_radverr2', label: 'Stellar Radial Velocity Lower Unc. [km/s]' },
    { value: 'st_radvlim', label: 'Stellar Radial Velocity Limit Flag' },
    { value: 'sy_refname', label: 'System Parameter Reference' },
    { value: 'rastr', label: 'RA [sexagesimal]' },
    { value: 'ra', label: 'RA [decimal]' },
    { value: 'decstr', label: 'Dec [sexagesimal]' },
    { value: 'dec', label: 'Dec [decimal]' },
    { value: 'raerr1', label: 'RA Upper Unc' },
    { value: 'raerr2', label: 'RA Lower Unc' },
    { value: 'decerr1', label: 'Dec Upper Unc' },
    { value: 'decerr2', label: 'Dec Lower Unc' },
    { value: 'glat', label: 'Galactic Latitude [deg]' },
    { value: 'glaterr1', label: 'Galactic Latitude [deg] Upper Unc' },
    { value: 'glaterr2', label: 'Galactic Latitude [deg] Lower Unc' },
    { value: 'glon', label: 'Galactic Longitude [deg]' },
    { value: 'glonerr1', label: 'Galactic Longitude [deg] Upper Unc' },
    { value: 'glonerr2', label: 'Galactic Longitude [deg] Lower Unc' },
    { value: 'elat', label: 'Ecliptic Latitude [deg]' },
    { value: 'elaterr1', label: 'Ecliptic Latitude [deg] Upper Unc' },
    { value: 'elaterr2', label: 'Ecliptic Latitude [deg] Lower Unc' },
    { value: 'elon', label: 'Ecliptic Longitude [deg]' },
    { value: 'elonerr1', label: 'Ecliptic Longitude [deg] Upper Unc' },
    { value: 'elonerr2', label: 'Ecliptic Longitude [deg] Lower Unc' },
    { value: 'sy_pm', label: 'Total Proper Motion [mas/yr]' },
    { value: 'sy_pmerr1', label: 'Total Proper Motion Upper Unc [mas/yr]' },
    { value: 'sy_pmerr2', label: 'Total Proper Motion Lower Unc [mas/yr]' },
    { value: 'sy_pmra', label: 'Proper Motion (RA) [mas/yr]' },
    { value: 'sy_pmraerr1', label: 'Proper Motion (RA) [mas/yr] Upper Unc' },
    { value: 'sy_pmraerr2', label: 'Proper Motion (RA) [mas/yr] Lower Unc' },
    { value: 'sy_pmdec', label: 'Proper Motion (Dec) [mas/yr]' },
    { value: 'sy_pmdecerr1', label: 'Proper Motion (Dec) [mas/yr] Upper Unc' },
    { value: 'sy_pmdecerr2', label: 'Proper Motion (Dec) [mas/yr] Lower Unc' },
    { value: 'sy_dist', label: 'Distance [pc]' },
    { value: 'sy_disterr1', label: 'Distance [pc] Upper Unc' },
    { value: 'sy_disterr2', label: 'Distance [pc] Lower Unc' },
    { value: 'sy_plx', label: 'Parallax [mas]' },
    { value: 'sy_plxerr1', label: 'Parallax [mas] Upper Unc' },
    { value: 'sy_plxerr2', label: 'Parallax [mas] Lower Unc' },
    { value: 'sy_bmag', label: 'B (Johnson) Magnitude' },
    { value: 'sy_bmagerr1', label: 'B (Johnson) Magnitude Upper Unc' },
    { value: 'sy_bmagerr2', label: 'B (Johnson) Magnitude Lower Unc' },
    { value: 'sy_vmag', label: 'V (Johnson) Magnitude' },
    { value: 'sy_vmagerr1', label: 'V (Johnson) Magnitude Upper Unc' },
    { value: 'sy_vmagerr2', label: 'V (Johnson) Magnitude Lower Unc' },
    { value: 'sy_jmag', label: 'J (2MASS) Magnitude' },
    { value: 'sy_jmagerr1', label: 'J (2MASS) Magnitude Upper Unc' },
    { value: 'sy_jmagerr2', label: 'J (2MASS) Magnitude Lower Unc' },
    { value: 'sy_hmag', label: 'H (2MASS) Magnitude' },
    { value: 'sy_hmagerr1', label: 'H (2MASS) Magnitude Upper Unc' },
    { value: 'sy_hmagerr2', label: 'H (2MASS) Magnitude Lower Unc' },
    { value: 'sy_kmag', label: 'Ks (2MASS) Magnitude' },
    { value: 'sy_kmagerr1', label: 'Ks (2MASS) Magnitude Upper Unc' },
    { value: 'sy_kmagerr2', label: 'Ks (2MASS) Magnitude Lower Unc' },
    { value: 'sy_umag', label: 'u (Sloan) Magnitude' },
    { value: 'sy_umagerr1', label: 'u (Sloan) Magnitude Upper Unc' },
    { value: 'sy_umagerr2', label: 'u (Sloan) Magnitude Lower Unc' },
    { value: 'sy_gmag', label: 'g (Sloan) Magnitude' },
    { value: 'sy_gmagerr1', label: 'g (Sloan) Magnitude Upper Unc' },
    { value: 'sy_gmagerr2', label: 'g (Sloan) Magnitude Lower Unc' },
    { value: 'sy_rmag', label: 'r (Sloan) Magnitude' },
    { value: 'sy_rmagerr1', label: 'r (Sloan) Magnitude Upper Unc' },
    { value: 'sy_rmagerr2', label: 'r (Sloan) Magnitude Lower Unc' },
    { value: 'sy_imag', label: 'i (Sloan) Magnitude' },
    { value: 'sy_imagerr1', label: 'i (Sloan) Magnitude Upper Unc' },
    { value: 'sy_imagerr2', label: 'i (Sloan) Magnitude Lower Unc' },
    { value: 'sy_zmag', label: 'z (Sloan) Magnitude' },
    { value: 'sy_zmagerr1', label: 'z (Sloan) Magnitude Upper Unc' },
    { value: 'sy_zmagerr2', label: 'z (Sloan) Magnitude Lower Unc' },
    { value: 'sy_w1mag', label: 'W1 (WISE) Magnitude' },
    { value: 'sy_w1magerr1', label: 'W1 (WISE) Magnitude Upper Unc' },
    { value: 'sy_w1magerr2', label: 'W1 (WISE) Magnitude Lower Unc' },
    { value: 'sy_w2mag', label: 'W2 (WISE) Magnitude' },
    { value: 'sy_w2magerr1', label: 'W2 (WISE) Magnitude Upper Unc' },
    { value: 'sy_w2magerr2', label: 'W2 (WISE) Magnitude Lower Unc' },
    { value: 'sy_w3mag', label: 'W3 (WISE) Magnitude' },
    { value: 'sy_w3magerr1', label: 'W3 (WISE) Magnitude Upper Unc' },
    { value: 'sy_w3magerr2', label: 'W3 (WISE) Magnitude Lower Unc' },
    { value: 'sy_w4mag', label: 'W4 (WISE) Magnitude' },
    { value: 'sy_w4magerr1', label: 'W4 (WISE) Magnitude Upper Unc' },
    { value: 'sy_w4magerr2', label: 'W4 (WISE) Magnitude Lower Unc' },
    { value: 'sy_gaiamag', label: 'Gaia Magnitude' },
    { value: 'sy_gaiamagerr1', label: 'Gaia Magnitude Upper Unc' },
    { value: 'sy_gaiamagerr2', label: 'Gaia Magnitude Lower Unc' },
    { value: 'sy_icmag', label: 'I (Cousins) Magnitude' },
    { value: 'sy_icmagerr1', label: 'I (Cousins) Magnitude Upper Unc' },
    { value: 'sy_icmagerr2', label: 'I (Cousins) Magnitude Lower Unc' },
    { value: 'sy_tmag', label: 'TESS Magnitude' },
    { value: 'sy_tmagerr1', label: 'TESS Magnitude Upper Unc' },
    { value: 'sy_tmagerr2', label: 'TESS Magnitude Lower Unc' },
    { value: 'sy_kepmag', label: 'Kepler Magnitude' },
    { value: 'sy_kepmagerr1', label: 'Kepler Magnitude Upper Unc' },
    { value: 'sy_kepmagerr2', label: 'Kepler Magnitude Lower Unc' },
    { value: 'rowupdate', label: 'Date of Last Update' },
    { value: 'pl_pubdate', label: 'Planetary Parameter Reference Publication Date' },
    { value: 'releasedate', label: 'Release Date' },
    { value: 'pl_nnotes', label: 'Number of Notes' },
    { value: 'st_nphot', label: 'Number of Photometry Time Series' },
    { value: 'st_nrvc', label: 'Number of Radial Velocity Time Series' },
    { value: 'st_nspec', label: 'Number of Stellar Spectra Measurements' },
    { value: 'pl_nespec', label: 'Number of Emission Spectroscopy Measurements' },
    { value: 'pl_ntranspec', label: 'Number of Transmission Spectroscopy Measurements' },
  ],
};

export const relevantColumnsByMissionNumerical = {
  TESS: [
    { value: 'pl_rade', label: 'Planet Radius [R⊕]' },
    { value: 'pl_orbper', label: 'Orbital Period [days]' },
    { value: 'pl_trandep', label: 'Transit Depth [ppm]' },
    { value: 'pl_trandurh', label: 'Transit Duration [hours]' },
    { value: 'pl_eqt', label: 'Planet Equilibrium Temperature [K]' },
    { value: 'pl_insol', label: 'Insolation [Earth flux]' },
    { value: 'st_tmag', label: 'TESS Magnitude' },
    { value: 'st_teff', label: 'Stellar Effective Temperature [K]' },
    { value: 'st_rad', label: 'Stellar Radius [R☉]' },
    { value: 'st_dist', label: 'Stellar Distance [pc]' },
  ],
  PS: [
    { value: 'pl_rade', label: 'Planet Radius [R⊕]' },
    { value: 'pl_massj', label: 'Planet Mass [MJ]' },
    { value: 'pl_orbper', label: 'Orbital Period [days]' },
    { value: 'pl_eqt', label: 'Equilibrium Temperature [K]' },
    { value: 'pl_insol', label: 'Insolation Flux [Earth flux]' },
    { value: 'pl_dens', label: 'Planet Density [g/cm³]' },
    { value: 'st_teff', label: 'Stellar Effective Temperature [K]' },
    { value: 'st_rad', label: 'Stellar Radius [R☉]' },
    { value: 'st_mass', label: 'Stellar Mass [M☉]' },
    { value: 'st_met', label: 'Stellar Metallicity [dex]' },
    { value: 'sy_dist', label: 'System Distance [pc]' },
    { value: 'sy_tmag', label: 'TESS Magnitude' },
  ]
};

export const relevantColumnsByMissionCategorical = {
  TESS: [
    { value: 'tfopwg_disp', label: 'TFOPWG Disposition' },
    { value: 'toi', label: 'TOI ID' },
    { value: 'ctoi_alias', label: 'Community Alias' },
  ],
  PS: [
    { value: 'discoverymethod', label: 'Discovery Method' },
    { value: 'disc_year', label: 'Discovery Year' },
    { value: 'hostname', label: 'Host Name' },
    { value: 'soltype', label: 'Solution Type' },
    { value: 'st_spectype', label: 'Spectral Type' },
  ]
}