export const constellations = [
  { value: "andromeda", label: "Andromeda" },
  { value: "antlia", label: "Antlia" },
  { value: "apus", label: "Apus" },
  { value: "aquarius", label: "Aquarius" },
  { value: "aquila", label: "Aquila" },
  { value: "ara", label: "Ara" },
  { value: "aries", label: "Aries" },
  { value: "auriga", label: "Auriga" },
  { value: "bootes", label: "Bootes" },
  { value: "caelum", label: "Caelum" },
  { value: "camelopardalis", label: "Camelopardalis" },
  { value: "cancer", label: "Cancer" },
  { value: "canes_venatici", label: "Canes Venatici" },
  { value: "canis_major", label: "Canis Major" },
  { value: "canis_minor", label: "Canis Minor" },
  { value: "capricornus", label: "Capricornus" },
  { value: "carina", label: "Carina" },
  { value: "cassiopeia", label: "Cassiopeia" },
  { value: "centaurus", label: "Centaurus" },
  { value: "cepheus", label: "Cepheus" },
  { value: "cetus", label: "Cetus" },
  { value: "chamaeleon", label: "Chamaeleon" },
  { value: "circinus", label: "Circinus" },
  { value: "columba", label: "Columba" },
  { value: "coma_berenices", label: "Coma Berenices" },
  { value: "corona_australis", label: "Corona Australis" },
  { value: "corona_borealis", label: "Corona Borealis" },
  { value: "corvus", label: "Corvus" },
  { value: "crater", label: "Crater" },
  { value: "crux", label: "Crux" },
  { value: "cygnus", label: "Cygnus" },
  { value: "delphinus", label: "Delphinus" },
  { value: "dorado", label: "Dorado" },
  { value: "draco", label: "Draco" },
  { value: "equuleus", label: "Equuleus" },
  { value: "eridanus", label: "Eridanus" },
  { value: "fornax", label: "Fornax" },
  { value: "gemini", label: "Gemini" },
  { value: "grus", label: "Grus" },
  { value: "hercules", label: "Hercules" },
  { value: "horologium", label: "Horologium" },
  { value: "hydra", label: "Hydra" },
  { value: "hydrus", label: "Hydrus" },
  { value: "indus", label: "Indus" },
  { value: "lacerta", label: "Lacerta" },
  { value: "leo", label: "Leo" },
  { value: "leo_minor", label: "Leo Minor" },
  { value: "lepus", label: "Lepus" },
  { value: "libra", label: "Libra" },
  { value: "lupus", label: "Lupus" },
  { value: "lynx", label: "Lynx" },
  { value: "lyra", label: "Lyra" },
  { value: "mensa", label: "Mensa" },
  { value: "microscopium", label: "Microscopium" },
  { value: "monoceros", label: "Monoceros" },
  { value: "musca", label: "Musca" },
  { value: "norma", label: "Norma" },
  { value: "octans", label: "Octans" },
  { value: "ophiuchus", label: "Ophiuchus" },
  { value: "orion", label: "Orion" },
  { value: "pavo", label: "Pavo" },
  { value: "pegasus", label: "Pegasus" },
  { value: "perseus", label: "Perseus" },
  { value: "phoenix", label: "Phoenix" },
  { value: "pictor", label: "Pictor" },
  { value: "pisces", label: "Pisces" },
  { value: "pisces_austrinus", label: "Pisces Austrinus" },
  { value: "puppis", label: "Puppis" },
  { value: "pyxis", label: "Pyxis" },
  { value: "reticulum", label: "Reticulum" },
  { value: "sagitta", label: "Sagitta" },
  { value: "sagittarius", label: "Sagittarius" },
  { value: "scorpius", label: "Scorpius" },
  { value: "sculptor", label: "Sculptor" },
  { value: "scutum", label: "Scutum" },
  { value: "serpens", label: "Serpens" },
  { value: "sextans", label: "Sextans" },
  { value: "taurus", label: "Taurus" },
  { value: "telescopium", label: "Telescopium" },
  { value: "triangulum", label: "Triangulum" },
  { value: "triangulum_australe", label: "Triangulum Australe" },
  { value: "tucana", label: "Tucana" },
  { value: "ursa_major", label: "Ursa Major" },
  { value: "ursa_minor", label: "Ursa Minor" },
  { value: "vela", label: "Vela" },
  { value: "virgo", label: "Virgo" },
  { value: "volans", label: "Volans" },
  { value: "vulpecula", label: "Vulpecula" },
];
